version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4 # Invoke the Heroku orb

jobs:
  build:
    docker:
      - image: circleci/node:14-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - portfolio-dependency-cache-v1-{{ checksum "package-lock.json" }}
            - portfolio-dependency-cache-v1-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: portfolio-dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Ensure App Builds
          command: npm run-script build

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Avoid Non-Deployment Updates
          command: |
              changes=`git show --name-only ${CIRCLE_SHA1} | tail -n +7`

              if [ "$changes" = ".circleci/config.yml" ] || [ "$changes" = "README.md" ]; then
                echo "Only found a configuration or documentation change. Stopping build"
                circleci-agent step halt
              fi
      - heroku/deploy-via-git

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch