version: 2.1
orbs:
  heroku: circleci/heroku@1.2.4 # Invoke the Heroku orb
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
workflows:
  version: 2
  build:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch